# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Feed-JavaScript
version:      0.01
version_from: lib/XML/Feed/JavaScript.pm
installdirs:  site
requires:
    Encode:                        0
    Encode::compat:                0.07
    HTML::Template:                0
    XML::Feed:                     0.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
